version: "3.9"

services:

  mma:
    image: rodtamin/modbus-memory-appliance:2.3.4
    container_name: mma
    restart: unless-stopped
    ports:
      - "502:502"
    volumes:
      - ./data/mma:/config
    command: ["/config/config.yaml"]
    networks:
      - replicator-net

  replicator:
    image: rodtamin/modbus-replicator:latest
    container_name: replicator
    restart: unless-stopped
    depends_on:
      - mma
    volumes:
      - ./data/replicator:/config
    command: ["/config/config.yaml"]
    networks:
      - replicator-net

networks:
  replicator-net:
    driver: bridge
