version: "3.9"

services:

  mma:
    image: rodtamin/modbus-memory-appliance:2.3.4
    container_name: mma
    restart: unless-stopped
    ports:
      - "502:502"
    volumes:
      - ./data/mma:/config
    command: ["/config/config.yaml"]
    environment:
      - APP_VERSION=${APP_VERSION:-dev}
    networks:
      - replicator-net

  replicator:
    image: rodtamin/modbus-replicator:latest
    container_name: replicator
    restart: unless-stopped
    depends_on:
      - mma
    volumes:
      - ./data/replicator:/config
    command: ["/config/config.yaml"]
    environment:
      - APP_VERSION=${APP_VERSION:-dev}
    networks:
      - replicator-net

  web:
    build:
      context: ./web
      args:
        - APP_VERSION=${APP_VERSION:-dev}
    image: rodtamin/mcs-web:${APP_VERSION:-dev}
    container_name: mcs-web
    restart: unless-stopped
    ports:
      - "8081:8080"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mma
      - replicator
    environment:
      - APP_VERSION=${APP_VERSION:-dev}
    networks:
      - replicator-net

networks:
  replicator-net:
    driver: bridge